=head1 Using Gearman with Catalyst to Create a Simple Image Thumbnailer

=head2 SYNOPSIS

L<Gearman> is a distributed job queue system that excels in doing things quickly, and asynchronously run job processes for things that need batch processesing, or those which you don't want your web application having to deal with.  It's quick, and good for things like thumbnailing, which we will be talking about today.

=head2 REQUIREMENTS

=over 12

=item L<Gearman::Server> 

This is the actual job server that keeps track of jobs, and what the worker processes connect to. Initialized with C<gearmand>.

=item L<Gearman::Worker>

This is your worker instance, which actually does the job you want done.  HINT:  We want to do thumbnailing, so this will contain the code for creating thumbnails from images.

=item L<Catalyst>

Duh.

=cut
